-- DROP DATABASE
DROP DATABASE IF EXISTS grrrrinder_db;

-- CREATE DATABASE --
CREATE DATABASE grrrrinder_db;

USE grrrrinder_db;
-- DROP DATABASE
DROP DATABASE IF EXISTS grrrrinder_db;

-- CREATE DATABASE
CREATE DATABASE grrrrinder_db;
